# Generated by Django 4.2.14 on 2025-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(help_text="Comma-separated values: e.g., 'Breakfast,Dinner'", max_length=100),
        ),
    ]
