# Generated by Django 4.2.14 on 2025-10-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_medicine_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='doctor',
        ),
    ]
