# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    CustomTokenObtainPairView,
    DoctorViewSet, 
    PatientViewSet, 
    BedViewSet, 
    AppointmentViewSet,
    MedicineViewSet,
    DiagnosisViewSet,
    UserInfoView,
    DebugDataView,
    DoctorAvailabilityView,
    PatientReportPDFView,
    TestPDFView
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'doctors', DoctorViewSet, basename='doctor')
router.register(r'patients', PatientViewSet, basename='patient')
router.register(r'beds', BedViewSet, basename='bed')
router.register(r'appointments', AppointmentViewSet, basename='appointment')
router.register(r'medicines', MedicineViewSet, basename='medicine')
router.register(r'diagnoses', DiagnosisViewSet, basename='diagnosis')

# The API URLs are now automatically generated by the router.
urlpatterns = [
    # Your existing auth URLs
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('user-info/', UserInfoView.as_view(), name='user_info'),
    path('debug-data/', DebugDataView.as_view(), name='debug_data'),
    path('doctor-availability/', DoctorAvailabilityView.as_view(), name='doctor_availability'),
    path('patient-report-pdf/<int:patient_id>/', PatientReportPDFView.as_view(), name='patient_report_pdf'),
    path('test-pdf/', TestPDFView.as_view(), name='test_pdf'),
    
    # Add the router-generated URLs
    path('', include(router.urls)),
]