# api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    CustomTokenObtainPairView,
    DoctorViewSet, 
    PatientViewSet, 
    BedViewSet, 
    AppointmentViewSet,
    MedicineViewSet,
    DiagnosisViewSet
)

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'doctors', DoctorViewSet, basename='doctor')
router.register(r'patients', PatientViewSet, basename='patient')
router.register(r'beds', BedViewSet, basename='bed')
router.register(r'appointments', AppointmentViewSet, basename='appointment')
router.register(r'medicines', MedicineViewSet, basename='medicine')
router.register(r'diagnoses', DiagnosisViewSet, basename='diagnosis')

# The API URLs are now automatically generated by the router.
urlpatterns = [
    # Your existing auth URLs
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    
    # Add the router-generated URLs
    path('', include(router.urls)),
]